# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=16)),
                ('client_code', models.CharField(max_length=16)),
                ('total', models.PositiveIntegerField()),
                ('acquisition_price', models.DecimalField(decimal_places=6, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=16)),
                ('last_price', models.DecimalField(decimal_places=6, max_digits=15)),
            ],
        ),
    ]
