# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=256)),
                ('buy_price', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('last_sell_price', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('target', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('cur_price', models.DecimalField(decimal_places=6, max_digits=15)),
            ],
        ),
    ]
