# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_resultview_perent_diff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultview',
            old_name='perent_diff',
            new_name='percent_diff',
        ),
    ]
