# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170131_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultview',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
