# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170203_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('has_dividends', models.BooleanField(default=False)),
                ('year_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='resultview',
            name='has_dividends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultview',
            name='year_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
