# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170203_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultview',
            name='divident_year_percent',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
